[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
target-version = "py311"
line-length = 100
exclude = [
  "venv",
  ".venv",
  "build",
  "dist",
  "**/__pycache__",
  "terminator/frameworks/react.py",  # Non-Python sample content
]
force-exclude = true

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "ASYNC", "B", "C4"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
