name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff pyright pytest
      - name: Ruff format (check only)
        run: ruff format --check .
      - name: Ruff lint (full repo)
        run: ruff check .
      - name: Pyright type check (full repo)
        run: pyright
      - name: Run tests
        run: pytest -q
